### ISSUE TITLE
Intersection verschiebt sich beim Wechsel von Simulator zu Editor

### ISSUE THREAD

**Issue by ghost** [Waldemarv/swt1718#9]
Wenn man eine Erstellte Map vom Simulator zurück in den Editor lädt, verschieben sich die Intersections, bei jedem wechsel um einen konstanten Wert.

**Comment by jpwahle** [comment]
[https://github.com/Waldemarv/swt1718/commit/e9ffc19ca24f66bd2f6221fbd637c0ba384bde74](url)
